<a href="https://colab.research.google.com/github/Kissuuu/Assignment_1/blob/main/AmanKhan_numpy_assignment_code_kong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment

## 1. Import numpy 

In [ ]:
import numpy as np

## 2. Create an array of 10 zeroes

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3. Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 4. Create an array of 10 fives

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of integers from 11 to 50

In [ ]:
np.arange(11,51)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50])

## 6. Create an array of all the even integers from 11 to 50

In [ ]:
np.arange(12,51,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50])

## 7. Create a 3 * 3 matrices of values from range 0 to 8 

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Use numpy to gentrate a number randomly between 0 and 1

In [ ]:
np.random.rand(10)

array([0.09868628, 0.31587189, 0.07571422, 0.53564016, 0.70797003,
       0.93753526, 0.93620363, 0.88716219, 0.9378748 , 0.73867238])

## Create the following matrices

### 20 linrarly spaced points between 0 and 2

In [ ]:
np.random.randn(20)

array([ 1.04861697,  0.67088734,  0.32675311, -1.31107306, -0.0637294 ,
        0.63806073,  0.08598878, -1.25607346,  0.51022399, -0.13453525,
        1.89085654, -1.54601356,  0.22095706, -0.5565705 , -0.33146189,
        0.46225044, -0.44388074, -0.77284453,  1.44216452,  0.75440604])

## Numpy indexing and selection

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Use the above matrices for the following set of questions

### 1. only first value of matrice mat

In [ ]:
mat[0,0]

1

### 2. middle value of matrice mat

In [ ]:
mat[2,2]

13

### 3. first two rows and last one column values of matrice mat

In [ ]:
mat[:2,4:]

array([[ 5],
       [10]])

### 4. last row and all column values of matrice mat

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])